// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;
console.log("SUPABASE_URL_RUNTIME", import.meta.env.VITE_SUPABASE_URL);
console.log("SUPABASE_KEY_RUNTIME", import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY);


export const supabase = createClient<Database>(
  String(SUPABASE_URL),
  String(SUPABASE_PUBLISHABLE_KEY),
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    },
  }
);
